flags: {}
extra-package-dbs: []
packages:
- '.'
# - '../rdf4h-vocabulary-generator/'
- location:
    git: https://github.com/fabianmeyer/rdf4h-vocabulary-generator.git
    commit: 8f098c48ddf0ef06652742632f813fd1fa8bc557
extra-deps:
- rdf4h-3.0.1
resolver: lts-8.13
