flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/fabianmeyer/rdf4h-vocabulary-generator.git
    commit: 41b7706870740329c05da4b2717e7f120b0ab21b
extra-deps:
- rdf4h-3.0.1
resolver: lts-8.13
